serverConf:
  name: "courseSystem"
  version: "0.0.1"
  host: "0.0.0.0"
  port: 8080
mysqlConf:
  user: "root"
  password: "119129"
  host: "175.178.218.166"
  port: 3306
  db: "pxjCourseSystem"
redisConf:
  host: "175.178.218.166"
  db: 4
  password: "119129"